load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "dosbox_lib",
    srcs = [
        "lib.rs",
        "dosbox.rs",
        "find.rs",
    ],
)
