load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "basic_lib",
    srcs = ["lib.rs"],
    deps = [
        "//dosbox_lib"
    ]
)
